version: '3.9'

services:
  db:
    image: postgis/postgis:14-3.1
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food_supplier_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-postgis.sh:/docker-entrypoint-initdb.d/init-postgis.sh  # Custom initialization script
    networks:
      - app_network

  web:
    build: .
    container_name: django_app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 uksc_backend_django.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      RUN_SEED: "false"
      DJANGO_SETTINGS_MODULE: uksc_backend_django.settings
      DEBUG: "False"
      ALLOWED_HOSTS: "your-railway-app-url.up.railway.app"
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
