# Generated by Django 5.1.4 on 2025-01-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('workers', models.IntegerField()),
                ('sector', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('source_business', models.CharField(max_length=100)),
            ],
        ),
    ]
