# Generated by Django 5.1.4 on 2025-01-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='workers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
