# Generated by Django 5.1.4 on 2025-01-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_supplier_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCountView',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('source_business', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('country_count', models.IntegerField()),
            ],
            options={
                'db_table': 'country_count_by_year_and_supermarket',
                'managed': False,
            },
        ),
    ]
